blank_issues_enabled: false
contact_links:
  - name: Questions et idées
    url: https://github.com/edwinfranck/regie/discussions
    about: Pour une question d'usage ou une idée à discuter avant une issue.
